use_frameworks!

source 'https://github.com/iOSModularization/AHFMSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'


target 'AHFMSearchVCManager_Example' do
  pod 'AHFMSearchVCManager', :path => '../'

  target 'AHFMSearchVCManager_Tests' do
    inherit! :search_paths

    
  end
end
